version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sambodb
    volumes:
      - postgres:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres:
